PhasesResearchLab/ESPEI

README.rst, espei/__init__.py, espei/core_utils.py, espei/fit.py, espei/paramselect.py, espei/plot.py, espei/utils.py
@richardotis Can you do a sanity check on the paramselect.fit() function paramselect.lnprob() function, the fit.py entry point, and the new stuff in utils? All the other changes should just be refactoring and should not have changed behavior.
=> Emcee support

docs/index.rst, espei/plot.py
Also moves the previous data plotting routines to dataplot, which can be used with eqplot or alone.
Closes #12
=> ENH/REF: Refactor multiplot into a phase diagram + data convenience plotter

docs/writing_input.rst, espei/input-schema.yaml, espei/run_espei.py, espei/tests/test_schema.py
=> Implement emcee multiprocessing

espei/plot.py
Rename dataplot -> eqdataplot, which is just a wrapper around the new
dataplot.
Dataplot now only plots *data* for comps, phases, conditions. eqdataplot
used to do this, but starting from a Dataset from equilibrium. Now
eqdataplot constructs comps, phases, conditions from Dataset objects.
dataplot now takes a plot_kwargs argument that can be used to control
the maplotlib arguments from the higher level APIs. While doing this,
the default scatter marker size was changed from 100 to 50.
=> ENH: Modify plot API to allow plotting of only data points, closes gh-36

espei/datasets.py, espei/tests/test_datasets.py, espei/tests/testing_data.py, espei/utils.py
Also makes `get_pure_elements` non-private
=>  FIX: Check datasets support for activity data. Closes #56

espei/__init__.py, espei/core_utils.py, espei/datasets.py, espei/error_functions/zpf_error.py, espei/espei_script.py, espei/mcmc.py, espei/paramselect.py
Also includes some minor formatting fixes
=> DOC: All code now has docstrings. Closes #35

espei/tests/test_error_functions.py, espei/tests/testing_data.py
=> TST: Test that an exactly correct tielines give a sum(error^2)=0

espei/core_utils.py, espei/datasets.py, espei/tests/test_core_utils.py, espei/tests/test_datasets.py, espei/tests/test_mcmc.py, espei/tests/testing_data.py
* Add recursive_map core util that maps recursively onto sublists
* Move some more testing data into the testing_data module
* Add ability to clean datasets where values are input as strings (JSON handling), added to dataset loader
Closes #67
=> ENH: Add dataset cleaner. Cleans expected numeric values to floats

espei/core_utils.py, espei/espei_script.py, espei/input-schema.yaml, espei/parameter_selection/model_building.py, espei/parameter_selection/redlich_kister.py, espei/parameter_selection/selection.py, espei/parameter_selection/ternary_parameters.py, espei/paramselect.py, tests/test_schema.py
Give users additional control over the penalty for number of parameters in AICc
=> ENH: Introduce AICc penalty factor

espei/espei_script.py, espei/input-schema.yaml, espei/optimizers/opt_mcmc.py, espei/utils.py
I made a few minor changes in the process of getting used to the code and running it myself.
=> Minor Changes

README.rst
Fix README logo size and malformed link
=> DOC: Update README

espei/plot.py
This PR:
* Adds tie-line flag to plotting
* Fixes a bug for low order system not being able to mass balance in dataplot
=> ENH: add dataplot tie-line flag

docs/contributing.rst, docs/installation.rst
* Link to Miniconda3 downloads
* Include discussion of JupyterLab installation
* Windows users: Git installation
* Development instructions: make an environment and point to the contributing guide
=> DOC: Update installation docs

espei/error_functions/zpf_error.py
`_sample_solution_constitution` was incorrectly using the independent site fractions that were already sampled as the expression for `sympy.lambdify`. In other words, `lambdify` was internally creating a loop over `grid_1d.size` constant valued "expressions", which would just be evaluated to the constant values, no matter the input. This could be really slow (~20 seconds for a `grid_1d.size` of 40,000).
This PR fixes the performance by checking that the expression is indeed a dependent site fraction expression rather than an independent sample that we already took.
Thanks to @wahab2604 for reporting this issue.
=> FIX: Fix performance of _sample_solution_constitution

CHANGES.rst, docs/advanced_schedulers.rst, docs/cu-mg-example.rst, docs/howto_use_custom_unary.rst, docs/index.rst, docs/input_data.rst, docs/quickstart.rst, docs/specifying_priors.rst, docs/writing_input.rst
* Rewrite phase diagram datasets section
* switch paper references to RST citations
* reorganize sections into how-to/reference material appropriately
=> DOC: Reorganize and update documentation

espei/error_functions/equilibrium_thermochemical_error.py, espei/error_functions/zpf_error.py, espei/shadow_functions.py
Integrate changes from https://github.com/pycalphad/pycalphad/pull/357.
=> MAINT: Update to use new pycalphad solver internals

espei/parameter_selection/selection.py
Improve the implementation of the AICc by better handling the case where the denominator in the correction term can become negative (small number of samples and a large number of parameters). With these changes, there is a smooth connection in the AICc rather than a discontinuity and a negative contribution to the correction term. In the spirit of the AICc, the AICc continues to increase with increasing number of parameters.
=> ENH: improve AICc formulation

espei/error_functions/zpf_error.py
Define the radius of points allowed in the sampling for constrained equilibria as the distance to the closest point + some additional distance to ensure that that's always at least one point in the sample.
This fixes the assertion failures when trying to get ZPF data for the constrained equilibrium calculations that could arise when the sampled points were not close enough to (within the tolerance of) the prescribed phase composition.
=> FIX: Improve sampling of ZPF points for constrained equilibria

.gitignore, espei/plot.py
- Update legends in `espei.plot` functions to be centered vertically on the right-outer edge of the plot
- Extract the plotting function for plotting predicted non-equilibrium thermochemical data (useful for repeated calculations with different sets of parameters in uncertainty propagation)
=> ENH: Extract the plotting function for plotting predicted non-equilibrium thermochemical data

espei/error_functions/activity_error.py
=> FIX: Correctly pass parameters through calculate_activity_error

espei/core_utils.py, espei/datasets.py, espei/error_functions/equilibrium_thermochemical_error.py, espei/error_functions/non_equilibrium_thermochemical_error.py, espei/error_functions/zpf_error.py, espei/optimizers/opt_mcmc.py, espei/parameter_selection/fitting_steps.py, espei/parameter_selection/selection.py, espei/plot.py, espei/priors.py, espei/shadow_functions.py, espei/utils.py, tests/test_error_functions.py, tests/test_mcmc.py
Migration via ruff `pip install ruff` then `ruff check --fix . --select NPY201`
=> NumPy 2.0 support

README.rst
PyPI does not allow file insertion for security reasons.
See https://github.com/pypa/readme_renderer/issues/304#issuecomment-2259039895
=> MAINT: Remove included figure from README
