PhasesResearchLab/ESPEI

- docs/cu-mg-example.rst
- espei/paramselect.py
- espei/run_espei.py
Because MCMC fitting is relatively long-running and RAM intensive, it is ideal to be able to restart from a previous calculation. 
Currently, to restart, a user would manually update the parameters in the database to the parameters with the lowest probability from the previous run, then use that set of parameters to initialize a new set of walkers.
Since we save the state of the chains as the tracefile anyways, we can use the chains to restart a run in emcee and avoid tuning the walker initialization parameters on restart.
To make this (and analysis) easier, chains and log probabilities are now written out as binaries, rather than text files. This preserves the shape with the number of chains, so the chain file is now of shape (k, n, p), where k is number of walkers, n is the preallocated …
> Allow for restarting

- espei/core_utils.py
- espei/tests/test_core_utils.py
- espei/tests/test_utils.py
- setup.py
* Add a test for a minimal examples of finding data with get_data
* Fix an old test for the new explicit existence
* Update setup.py to require tinydb>=3
> FIX: support TinyDB 3 by not changing configuration tuple to list in get_data

- docs/conf.py
- espei/plot.py
- espei/tests/fixtures.py
- espei/tests/test_utils.py
- espei/utils.py
- setup.py
Closes gh-23.
- Adds a TinyDB bibliographic database and utilities to add a BibTeX entries to it
- bibtexparser is now a dependency
- Better handling of aliases in dataplot plot_kwargs
- Utility to read multiline strings from raw strings, file paths, or streams
Note that there is no functionality here to format the references based on the database, but this functionality could easily be added with some handling of the references by using a formatting function that takes a BibTeX dict.
> ENH: Add markers for each unique reference to dataplot

- espei/plot.py
* Docstrings for plot_parameters, _compare_data_to_parameters
* Allow Axes objects to be passed in to _compare_data_to_parameters
(cleanup of fig.gca() calls)
* Refactor plot_parameters to use subplots of a figure (take a figure
as a parameter)
* Scaffold some code for allowing parameters to be plotted without a
figure. This doesn't work for some edge cases of formation data, so
it is added as a todo
* Support bibliography markers for single phase plot_parameters
* Support plotting interaction parameters without comparison data
> ENH: Improve single phase parameter plotting

- espei/core_utils.py
- espei/plot.py
- Add a ravel_conditions method to unpack the conditions in ESPEI datasets
- Add method to unpack the ZPF data into easily plottable data
- Propagate this new method back to the X vs. T plots
- Enable plotting of tielines in 2 and 3 component systems
> ENH: Enable plotting of isothermal ZPF data in dataplot

- espei/paramselect.py
Use the AICc formulation, which corrects for low sample sizes.
Also use a more correct form of the log likelihood.
Closes #49
> ENH: Use AICc

- espei/error_functions/activity_error.py
- espei/error_functions/thermochemical_error.py
- espei/tests/test_error_functions.py
- espei/tests/testing_data.py
* FIX: Fix incorrectly sized pycalphad P/T/points arrays for MCMC thermochemical error
* TST: Includes tests for 3 datasets with varying X, T, T and X
* FIX: Fix error where SymPy NaNs in calculate_activity_error would raise in emcee (convert them the NumPy NaNs)
> FIX: Fix MCMC thermochemical error for P/T/points arrays

- docs/installation.rst
- espei/espei_script.py
- setup.py
In version 0.18, dask updated the configuration file. This change supports the new version of dask and distributed, checking the work-stealing correctly.
Closes #66
> FIX: Update to use dask>=0.18

- docs/contributing.rst
- docs/cu-mg-example.rst
- docs/mpi.rst
- docs/quickstart.rst
- docs/writing_input.rst
- espei/analysis.py
- espei/espei_script.py
- espei/input-schema.yaml
- espei/mcmc.py
- espei/tests/test_schema.py
Input and internal ESPEI APIs were often confused whether to call the MCMC trace of chains, iterations and parameters a "chain" or a "trace".
This commit makes it so that every time we are talking about all the chains together, we refer to it as the "trace", but when we refer to an individual chain the trace, we call it a "chain".
Additionally, the "mcmc.mcmc_steps" was renamed to "mcmc.iterations" to avoid redundancy and improve clarity. "mcmc.mcmc_save_interval" was similarly updated to "save_interval".
The input file, docs and Python API all reflect these changes.
> MAINT: Improve input consistency

- espei/plot.py
Currently, there are lines that connect data when there are more than 10 datapoints in a dataset. This is kind of distracting and not very useful over just data points, so it's removed.
Plotting HM_FORM is kind of redundant with HM_MIX (which plots formation data) and can't plot the actual mixing data (because we don't have a way to specify a reference state). So it's removed.
> ENH: Remove line (for >10 data points) and remove HM_FORM plot in plot_parameters

- .travis.yml
Python 3.8 is added to the test matrix (we test Python 3.6, 3.7 and 3.8 now). Testing against pycalphad development versions is also added, so development features in ESPEI that depend on development versions of pycalphad can be tested in CI (both pycalphad releases on conda-forge and pycalphad development versions from GH).
> TST: Add Python 3.8 and pycalphad release/nightly to the CI matrix

- .travis.yml
- docs/writing_input.rst
- espei/error_functions/context.py
- espei/error_functions/zpf_error.py
- espei/espei_script.py
- espei/input-schema.yaml
- espei/optimizers/opt_mcmc.py
- espei/plot.py
- espei/shadow_functions.py
- tests/test_error_functions.py
- tests/test_mcmc.py
- tests/test_schema.py
Calculating the driving force error for phase boundary data is typically the most computationally intensive part of running ESPEI.
** Requires https://github.com/pycalphad/pycalphad/pull/264 to run these commits in parallel!**
This PR tries to optimize (and simplify) calculating the ZPF error by doing the following:
1. Introduces a `PhaseRegion` NamedTuple that describes the data to calculate for each phase boundary set, instead of passing around all the data lists disparately. 
* This significantly reduces the complexity of the driving force calculation. 
* The `PhaseRegion` gets its own PhaseRecords for the calculation and contains all the relevant equilibrium arguments for that specific data. This therefore fixes a bug for mixing data types across different systems, e.g. fitting a …
> ENH: Optimize ZPF error calculation and provide an approximate ZPF driving force

- docs/quickstart.rst
- docs/recipes.rst
- docs/writing_input.rst
- espei/error_functions/activity_error.py
- espei/error_functions/zpf_error.py
- tests/test_error_functions.py
- tests/testing_data.py
If a user wants to fit a subsystem of their database, this code and tests ensures that everything still works.
In summary:
* Activity data works as normal. For activity data, the phases come from the dataset. All active phases are filtered through pycalphad's `filter_phases` function, to ensue that no phases that cannot be active with the components subset are active.
* Non-equilibrium thermochemical data: extra internal degrees of freedom are padded as zeros when constructing points.
> FIX: Add explicit support and tests for subsystems

- docs/index.rst
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
- tests/test_error_functions.py
- tests/testing_data.py
* Fix bug where failing equilibrium calculations in ZPF error raised. This bug was introduced by c81a7d3, when it refactored the performance of calls to logpdf.
* Add explicit tests that verify having SPECIES defined works for calculating phase boundary error. Everything was working, but I've added pycalphad's `unpack_components` in a few key places to make sure that changes in the pycalphad source that don't call `unpack_components` will continue to workin the future.
* Add tests asserting phase boundary data where approximate compositions are input for stoichiometric compounds with infinitely repeating decimal compositions gives the correct likelihood when only that phase becomes stable.
> FIX: Harden ZPF error, fix bug in failing equilibrium calls.

- espei/analysis.py
- espei/optimizers/opt_mcmc.py
- espei/utils.py
Users who had any zeros in their initial parameters would see an error when calling `optimal_parameters` ending in:
```python
File "/Users/brandon/Projects/espei/espei/utils.py", line 110, in optimal_parameters
for i in range(nz[-1][-1]):
IndexError: index -1 is out of bounds for axis 0 with size 0
```
The trace and lnprob arrays are initialized to zeros, so an intermediate trace or lnprob will be back-padded with zeros. This issue (and a corresponding issue in `truncate_arrays`) was caused by the code for finding the last iteration checking that `all` parameters were non-zero, when a more appropriate heuristic for finding the last iteration is to check that `any` parameters are non-zero. Note that `truncate_arrays` would fail silently, removing all the iterations from the trace (and …
> FIX: Update `truncate_arrays` and `optimal_parameters` to allow some zeros

- .travis.yml
- espei/datasets.py
- espei/error_functions/__init__.py
- espei/error_functions/context.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
- espei/optimizers/opt_mcmc.py
- espei/shadow_functions.py
- tests/test_datasets.py
- tests/test_error_functions.py
- tests/test_mcmc.py
- tests/testing_data.py
This PR adds support 
Outstanding TODO:
WONTFIX for this PR:
* There is no support for per-phase properties. All properties must have coordinates of only N, P, T, X(i).
> Preliminary support for thermochemical error for arbitrary properties

- docs/installation.rst
- espei/espei_script.py
- espei/utils.py
Having users turn off work-stealing in dask/distributed configuration files after setup was a nuisance. 
Now with https://github.com/dask/dask/pull/6647, dask no longer writes out commented out configuration files by default and work stealing is even more difficult for users to toggle off permanently in the filesystem. 
This PR turns off work-stealing in code on import of `espei_script.py` so users do not have to do it themselves and removes the now obsolete documentation for how to change the configuration files.
This PR also removes a duplicate definition of `get_dask_config_paths`.
> Override distributed work-stealing to False in code at runtime

- espei/espei_script.py
- espei/utils.py
dask/distributed configuration files can separate words with hyphens or underscores, e.g. `dask.config['distributed']['scheduler']['work-stealing']` and `dask.config['distributed']['scheduler']['work_stealing']` are both possibly valid. The correct API to check for `work_stealing`/`work-stealing` is `dask.config.get('distributed.scheduler.work-stealing')` where the `get` function will find the correct `-`/`_` as necessary.
> FIX: Improve check for dask's work-stealing

- espei/core_utils.py
- espei/datasets.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
- espei/parameter_selection/selection.py
- espei/parameter_selection/ternary_parameters.py
- espei/parameter_selection/utils.py
- espei/paramselect.py
- espei/plot.py
- espei/sublattice_tools.py
- espei/utils.py
- tests/test_error_functions.py
- tests/test_mcmc.py
The changes are backwards compatible to before numpy v1.13 (pycalphad's minimum).
See https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated for more details.
> MAINT: Fix numpy v1.20 deprecations.

- espei/error_functions/activity_error.py
This fixes an issue where phases containing non-pure element species would get filtered out of the phases list.
> FIX: Activity error: unpack components to properly get all Species objects

- .github/workflows/test_espei.yaml
- docs/contributing.rst
- setup.cfg
This adds default test locations `espei` and `tests` and adds the `--doctest-modules` option. 
The CI tests are updated and the docs are updated to reflect this.
> MAINT/TST: Add pytest configuration

- .gitignore
- espei/database_utils.py
- espei/datasets.py
- espei/espei_script.py
- tests/test_parameter_generation.py
Previously we used to recommend that datasets be disabled by either moving them out of the path or by changing their file extension from `.json` to something else, like `.json.disabled`. 
This PR aims to enable datasets to be disabled by using the `disabled: False` in the top level of JSON datasets, which allows for cleaner and more programmatic access.
> ENH: Allow for disabling datasets using JSON

- espei/database_utils.py
- tests/test_database_utils.py
Fixes a bug introduced by #158 where GHSER data was set to zero. Includes a test.
> FIX: Fix setting GHSER__ to zero in database initialization

- espei/datasets.py
- espei/espei_script.py
- tests/test_datasets.py
The `add_ideal_exclusions` function was added by #102 in June 2019 and was also deprecated at that time for removal in ESPEI 0.8. This function and its usages are now removed in favor of manually adding the exclusions or using tags.
> MAINT: Remove automatically adding ideal exclusions

- environment-dev.yml
- environment.yml
- espei/utils.py
- setup.py
- tests/test_utils.py
`flexible_open_string` and `add_bibtex_to_bib_database` were feature ideas that never caught on. `popget` doesn't do anything that the stdlib dictionary doesn't.
`bibtexparser` is removed as a dependency.
> MAINT: Remove dead utilities

- espei/parameter_selection/selection.py
- espei/paramselect.py
- tests/test_parameter_generation.py
Model selection residuals were calculated by multiplying weights by the observed value instead of the difference between the calculated and observed values. This may have led to incorrectly calculated AICc values because the weighted residuals would be incorrect.
This PR introduces a validating test that failed for the weighted L1 case before the fix.
> FIX: Fix weighting in model selection

- docs/quickstart.rst
- docs/recipes.rst
- espei/plot.py
The overall functionality of `plot_parameters` is now contained in `plot_interaction` and `plot_endmember` which are more clear about the form. The design of these now plots one property at a time on given axes. Both functions expose options to customize how matplotlib plots predicted values and observed values. Closes #60.
The new API is superior because there's more fine control over which properties are plotted, regardless of the existing data and whether `require_data` is passed or not.
To recover the full functionality of `plot_parameters` where multiple plots are in the same figure, users should use matplotlib subplots.
bar charts comparing data to parameters are no longer possible because they are an uncommon plot type and not usually seen in publications. They are not much more …
> Refactor `plot_parameters` into `plot_interaction` and `plot_endmember`

- CHANGES.rst
- espei/parameter_selection/utils.py
- tests/test_parameter_generation.py
Using a set prevents double-counting exclusions. Includes a test.
> FIX: parameter selection: use set of excluded model contributions

- .gitignore
- .readthedocs.yml
- docs/conf.py
* RTD config: Switch off building `all` formats, since LaTeX builds are failing (#167)
* Cleanup ESPEI development `|version|` information to remove the `.dirty` from the version since RTD dirties the version info
> DOC: ReadTheDocs: disable LaTeX formats and cleanup version info

- CHANGES.rst
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
* Make `PhaseRegion` a dataclass
* Introduce a `RegionVertex` dataclass instead of storing the vertex data in lists of `PhaseRegion`
* Fix a regression in ZPF data introduced by #151 where prescribed phase compositions of stoichiometric phases that used to work no longer work because the phase composition of a stoichiometric phase may be unsatisfiable. Now there's a check for stoichiometric phases that will not try to solve for the points.
* Fixes a bug where stoichiometric phases used `equilibrium` in driving force calculations which could give bad energies for exact equilibrium where mass balance could not be satisfied (approximate was not affected). Now exact and approximate equilibrium use driving force estimation via `calculate` which is always exact for stoichiometric phases because …
> FIX: Refactor PhaseRegion; better stoichiometric phase support

- CHANGES.rst
- espei/plot.py
Fix a regression where `plot_interaction` and `plot_endmember` re-used reference labels and markers
> FIX: Fix endmember/interaction plot labeling

- espei/core_utils.py
- espei/datasets.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/paramselect.py
- espei/plot.py
- tests/test_core_utils.py
These changes
1. further unify querying datasets between parameter selection/plotting and MCMC non-equilibrium thermochemical data
2. add a type alias for datasets as `Dataset`
> MAINT: Remove `get_data` from plotting/parameter selection

- espei/error_functions/context.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
- espei/shadow_functions.py
- tests/test_error_functions.py
- tests/test_mcmc.py
- tests/test_parameter_generation.py
Migrating to the new API for `pycalphad.core.calculate._sample_phase_constitution` removed the need for Database objects in error functions.
> MAINT: Remove Database objects from `calculate_` and error functions

- espei/error_functions/zpf_error.py
Restrict the single phase candidate points by only choosing points that are within specified (currently hardcoded) mass residual from the target composition. This should make the starting points better (closer to the target composition, which may be in a miscibility gap and relatively high in energy) and give fewer points to check to find the starting point in the first place.
> ENH: Better heuristic starting points for constrained driving force equilibrium

- espei/error_functions/context.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/zpf_error.py
- espei/espei_script.py
- espei/optimizers/opt_mcmc.py
- espei/utils.py
- tests/test_error_functions.py
The idea is that phase models can now have an optional `"model"` key for each phase that is a fully qualified import path to a class that follows pycalphad's Model protocol.
```json
{
"components": ["CU", "MG", "VA"],
"phases": {
"LIQUID" : {
"sublattice_model": [["CU", "MG"]],
"sublattice_site_ratios": [1],
"model": "mypackage.mymodule.MyModel"
},
"FCC_A1": {
"sublattice_model": [["CU", "MG"], ["VA"]],
"sublattice_site_ratios": [1, 1]
}
}
}
```
> ENH: Enable custom Model classes in MCMC

- espei/shadow_functions.py
Incorporates the changes to the Dataset/LightDataset API introduced in https://github.com/pycalphad/pycalphad/pull/362.
> MAINT: Update calculate shadow function for adding metastable composition sets

- espei/error_functions/zpf_error.py
PhaseRecord objects no longer depend on multi-phase conditions (specifically, `v.X`), so they can be built once per dataset (really once per set of components), rather once per vertex.
This may lead to decreased time in getting ZPF data and the memory consumption of ESPEI if there are many vertices in few datasets.
> ENH: ZPF error: pull `build_phase_records` out of the vertex loop

- .github/workflows/tests.yaml
Python 3.10 not supported by some runtime dependencies yet (see https://github.com/pycalphad/pycalphad/pull/374).
> BLD/MAINT: Pin Python version for sphinx-build action

- docs/input_data.rst
- espei/parameter_selection/selection.py
- setup.py
The `normalize` parameter was deprecated in scikit-learn 1.0. It does no take effect when `fit_intercept=False` (which we have always used), so we can simply remove it. See https://scikit-learn.org/1.0/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression for more details.
> MAINT: scikit-learn: remove normalize parameter

- docs/cu-mg-example.rst
- docs/recipes.rst
- espei/plot.py
Use of projections in `gca(projection=...)` are deprecated and more modern matplotlib seems to recommend `plt.subplot` instead of `gca` and `plt.subplots` to create new figures and axes.
> MAINT: Remove all matplotlib gca() calls

- espei/sublattice_tools.py
- tests/test_model_building.py
Complete rewrite of the `generate_symmetric_group`, preserving the existing API.
- Fixes a bug where the permutations of a 4 sublattice fcc phase with symmetry `[[0, 1, 2, 3]]` was only doing an `np.roll` of the sublattice indices, instead of permuting them. That is, we were producing `[0, 1, 2, 3]`, `[1, 2, 3, 0]`, `[2, 3, 0, 1]`, and `[3, 0, 1, 2]`, but missing the cases where the relative order changed like `[1, 0, 2, 3]` or `[0, 1, 3, 2]`. 
By supporting the ability to have non-specified sublattices to be fixed (e.g. in the case of an unspecified vacancy sublattice), we are trading off the ability to error check that all the sublattice indices are accounted for exactly once. A possible alternative is to force all sublattice indices to be given in symmetry, such as `[[0, 1, 2, 3], [4], …
> FIX: Fix generate_symmetric_group for FCC 4SL

- espei/shadow_functions.py
Update to the new internal pycalphad API from https://github.com/pycalphad/pycalphad/pull/415
> MAINT: Update for CompositionSet-based PyCalphad solver

- docs/api/espei.error_functions.rst
- docs/api/espei.rst
- espei/constants.py
- espei/error_functions/activity_error.py
- espei/error_functions/context.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/residual_base.py
- espei/error_functions/zpf_error.py
- espei/optimizers/opt_mcmc.py
- espei/optimizers/opt_scipy.py
- espei/phase_models.py
- espei/typing.py
- espei/utils.py
- pyproject.toml
- setup.py
- tests/test_error_functions.py
- tests/test_mcmc.py
This PR is a pretty substantial internal refactor and probably needs a close look by anyone modifying or developing new likelihood functions. I tried to only make light changes to existing likelihood functions and implement this new functionality around what already exists. @HUISUN24: this will probably affect #234, but hopefully will make it much simpler and your changes will have to touch many fewer places in the code. @jorgepazsoldanpalma will probably want to look too, but hopefully this doesn't affect you too much.
This PR introduces a `ResidualFunction` class to abstract the concept of residual/likelihood functions for different types of data. This allows new residual functions to be defined (both internally and externally) and registered for dynamic use. The `ResidualFunction` …
> ENH/MAINT: Refactor residual/likelihood functions

- espei/plot.py
- tests/test_plotting.py
Isothermal ternaries were broken by #240 by a bad error check that the `y` variable was temperature. For ternary triangular projections, both `x` and `y` should be molar quantities (i.e. `v.X()`). Both temperature and pressure need to be fixed scalars and therefore the filtering for `ravel_zpf_values` should be filtering against both potentials.
> FIX: Fix isothermal ternary projection dataplots

- espei/phase_models.py
- setup.py
Fix use of `Optional[PyObject]` by setting an explicit default which is now required in pydantic v2
> BLD: Support pydantic v2

- espei/optimizers/opt_mcmc.py
- tests/test_mcmc.py
I've attempted to patch issue #243. Running pytest before/after the patch I get the same number of errors, i.e. 
```
collected 300 items
espei/analysis.py .                                                                                              [  0%]
espei/datasets.py .                                                                                              [  0%]
espei/espei_script.py .                                                                                          [  1%]
espei/plot.py ssss                                                                                               [  2%]
espei/priors.py ....                                                                                             [  3%]
espei/sublattice_tools.py .. …
```
> Add initial/mean point to chains to fix #243

- .github/workflows/tests.yaml
- espei/error_functions/activity_error.py
- espei/error_functions/equilibrium_thermochemical_error.py
- espei/error_functions/non_equilibrium_thermochemical_error.py
- espei/error_functions/residual_base.py
- espei/error_functions/zpf_error.py
It seems that Python 3.11 changed the behavior of calling `super().__init__` for `Protocol` subclasses that have `Optional` arguments and subclasses of the `Residual` protocol are raising. 
This PR adds Python 3.11 to the CI test matrix and fixes the protocol signature (making the optional arguments actually optional) and also updates the callers that had incorrect signatures.
> FIX: Fix Residual protocol for MCMC for Python 3.11

- espei/core_utils.py
- espei/plot.py
- tests/test_plotting.py
The presence of `__HYPERPLANE__` overall compositions in datasets was causing the dimensionality of tie-regions to be artificially increased. For example, a 3 phase region with an additional __HYPERPLANE__ overall composition was being categorized as a 4 phase region and not plotted. This did not affect binary dataplotting because we did not differently depending on the number of phases in tie-regions (in ternary dataplotting we draw three phase regions as red tie-triangles).
> FIX: fix dataplot for ternary cases with __HYPERPLANE__

- espei/error_functions/non_equilibrium_thermochemical_error.py
- tests/test_error_functions.py
- tests/testing_data.py
If a fixed site fraction dataset has duplicated excluded model contributions, (which can happen if applying the same contribution in two different tags, for example), e.g.
```json
{
"components": ["CU","MG"],
"phases": ["CUMG2"],
"solver": {
"mode": "manual",
"sublattice_site_ratios": [1,2],
"sublattice_configurations": [["CU","MG"]]
},
"conditions": { "P": 101325, "T": 298.15},
"output": "SM_FORM",
"values": [[[-4.4]]],
"reference": "Estimated from Zhou (2007)",
"bibtex": "zhou2007",
"comment": "Estimated from enthalpy by s=h/3000",
"excluded_model_contributions": ["idmix", "mag", "idmix", "mag"]
}
```
the current behavior of the code will result in the excluded model contribution query failing and the dataset gets filtered out.
This change resolves that behavior.
> FIX: Dataset exclusion query for duplicated excluded model contributions

- espei/plot.py
This PR updates the fixed `phase_legend` function in `dataplot` to `legend_generator`. This enhancement allows customized phase legend generator used in `pycalphad.mapping.plotting` can be integrated into `dataplot` for plotting ZPF data in the phase diagram.
> ENH: Add phase legend generator in dataplot 

- .github/workflows/tests.yaml
- espei/refdata.py
Importing of `pkg_resources` is deprecated.
https://setuptools.pypa.io/en/latest/pkg_resources.html
The new way to handle plugins is illustrated below:
```python
def discover_pytest_plugins_old():
"""Find installed pytest plugins using pkg_resources"""
import pkg_resources
plugins = {}
for entry_point in pkg_resources.iter_entry_points('pytest11'):
try:
plugin = entry_point.load()
plugins[entry_point.name] = plugin
print(f"Found plugin: {entry_point.name}")
except Exception as e:
print(f"Failed to load plugin {entry_point.name}: {e}")
return plugins
def discover_pytest_plugins_new():
"""Find installed pytest plugins using importlib.metadata"""
from importlib.metadata import entry_points
plugins = {}
eps = entry_points(group='pytest11')
for entry_point in eps:
try:
plugin = …
```
> removed `pkg_resources`
